### ISSUE TITLE
Navigating the tachyons docs 

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-tachyons#17]
The tachyons docs are really _great_ so there is no need to rehash the documentation within this `learn` repo. However, there's a lot up there and for beginners, it *might* be useful to have a little 'getting started with the docs' if you're _learning_ tachyons as opposed to using the docs for reference.

What are people's thoughts on this? Will it just make the `learn-tachyons` repo stale quicker as the docs change?

**Comment by nelsonic** [comment]
@iteles I was thinking the _same_ thing; the docs are great but it would be good to _condense_ them into a "Learn this first" list.

**Comment by iteles** [comment]
Closed with the above commits for now, can be reopened when required 👍
