### ISSUE TITLE
The future of Tachyons video has been removed from youtube 

### ISSUE THREAD

**Issue by gabrielperales** [dwyl/learn-tachyons#23]
When I click on the link [https://youtu.be/XX47atVcVZE?t=1h1m11s](https://youtu.be/XX47atVcVZE?t=1h1m11s), youtube tells me that video was removed

**Comment by nelsonic** [comment]
@gabrielperales thanks for reporting this ... 😞 
Bug confirmed:
![image](https://cloud.githubusercontent.com/assets/194400/26518670/e38886b2-42ac-11e7-8f20-0e095c5f3272.png)

@markwilliamfirth any ideas _why_ this happened? 😕  (_thanks in advance for investigating..._)

**Comment by nelsonic** [comment]
I just clicked on the link to re-test and it _worked_ (_for me_). 🎉 
@gabrielperales please _confirm_ if you are able to open/view it and close if ok. (_thanks!_)

**Comment by gabrielperales** [comment]
@nelsonic yeah, it works now. Thanks for fixing it.
