### ISSUE TITLE
Add viewport to examples

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-tachyons#25]
I know they're just examples, but it would be good to amend them to include the `viewport` meta tag for a potentially improved mobile experience:
`<meta name=viewport content="width=device-width, initial-scale=1">`

See here for more: https://developers.google.com/speed/docs/insights/ConfigureViewport

**Comment by cwonrails** [comment]
Did this get addressed in https://github.com/dwyl/learn-tachyons/commit/79072d3430e4f8397a24df36fdfe4ae73a04d1d4 ? If not let me know and I'll get right on it!

**Comment by iteles** [comment]
It did! That was an _excellent_ PR, thanks @cwonrails :tada:
