### ISSUE TITLE
Remove reference of Pure CSS from index.html

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-tachyons#35]
We seem to have a reference to pure CSS here (most likely a copy-paste issue): https://github.com/dwyl/learn-tachyons/blob/master/index.html#L7

This should be removed for clarity 👍

**Comment by cwonrails** [comment]
Done! https://github.com/dwyl/learn-tachyons/commit/760817bba131e6367eb96a79438b62a706ddf847

**Comment by iteles** [comment]
Thanks @cwonrails!  :zap:

We're slowly slowly protecting `master` branches to prevent direct commits (this isn't a big deal for this small change but has been a real pain for us in the past) so thank you also for that reminder 😉
