### ISSUE TITLE
When?

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-tachyons#4]
It's useful to include a section on *when* to use tachyons (in the spirit of 'not every framework is the right tool for every project). This is a good write-up: http://simurai.com/blog/2016/11/27/css-methodologies

**Comment by nelsonic** [comment]
@iteles ***`Yes`*** totally agree this is a _crucial_ section in the readme.
***`And`*** we should _probably_ add a ***`When?`*** section to _all_ our `learn-...` tutorials to give people _context_. (_thanks for reminding us!_)

I think it's worth getting @olizilla's _insight_ on this. He shares his views on Tachyons in the First Episode of the @TableFlip Podcast https://player.fm/series/tableflip/spacer-wars 🎧 
(Oli's views are summarised in the first 2 mins in case you need a _reminder_...)

**Comment by olizilla** [comment]
We use it on projects where we have to come up with the look and feel of the site. When you've got wireframes or just raw ideas, and you want to develop the design as you go. We use it where we would have previously used bootstrap.**

If you have a designer on the team, then you should see if their ideas match up with those baked into tachyons before jumping in, if it's a good fit, then ✨. If not, it's a good set of ideas to discuss, and come up with your own styles from. 

My main advice is to use the methodology behind tachyons pretty much everywhere. The pattern... capturing the CSS properties you need with a range of values that make sense in your app has radically improved our workflow. Building up your own, tachyons inspired stylesheet, with just the properties you use leaves you with a css file that reads like a style guide. I think @mrmrs would agree.

**It's not a straight swap. Tachyons provides a strong design-centric guide without prescribing an aesthetic. It's like a great introduction to the features of CSS that you'll need to understand to build a pleasing layout, along with recommendations for values that work well together. It doesn't give you a modal widget that you can drop into an app. (modals are a ui of last resort, but sometimes you have to). Building your components up from tachyons basics means you understand them. Adopting bootstrap can mean you get a lot of components on the screen quickly, but adapting them can be hard.

The more proficient you get with the tachyons style, the less it matters. Building up your own components by harvesting ideas and tricks from rebass and boostrap and the tachyons examples makes front-end coding fun again.

**Comment by nelsonic** [comment]
@olizilla thanks (_so much!_) for sharing your insights on how you use Tachyons @Tableflip! ❤️ 
If you get time, please read through the readme and let us know if it's _beginner-friendly_
and if there's anything you would add please open an issue so we can improve it! 👍
