### ISSUE TITLE
Does Tachyons have a Logo?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tachyons#5]
Busy updating the "Stack Diagram": https://github.com/dwyl/technology-stack/issues/1
for "New Stack" https://github.com/dwyl/technology-stack/issues/37
and was wondering if Tachyons has a Logo... 🤔 
When I visit http://tachyons.io/ all I see is: 
![image](https://cloud.githubusercontent.com/assets/194400/22999317/a54c8a02-f3d2-11e6-8e05-abb4601b170d.png)

Which is very "clean" and "functional" ... but also "_unbranded_".
CC: @mrmrs 😉

**Comment by nelsonic** [comment]
found: https://sites.google.com/site/teaminvestigatetachyons/
![image](https://cloud.githubusercontent.com/assets/194400/22999236/4e841eb0-f3d2-11e6-9b1d-09a6bf429217.png)
So I took the [Lithium Atom Logo](http://www.reactrally.com/assets/dist/img/ReactLogo.svg)
Converted it to PNG: http://svgtopng.com/
Then replaced the "O" in the "TACHYONS" and get:
![tachyons-logo-new](https://cloud.githubusercontent.com/assets/194400/22999676/b12463ca-f3d4-11e6-9dd7-464e481e7675.png)
I _agree_ it's not particularly good, but we need _something_ for a presentation tomorrow. 
we can _always_ update later when there's something better. 👍

**Comment by mrmrs** [comment]
Checkout our header image on http://tachyons.io/gallery/

**Comment by nelsonic** [comment]
@mrmrs that's _way_ bettererer! _thanks!_ updating now!
![image](https://cloud.githubusercontent.com/assets/194400/23000323/f3886b8c-f3d7-11e6-880f-3ed39521c786.png)

**Comment by justgage** [comment]
This should totally be on the homepage.

**Comment by nelsonic** [comment]
![tachyons-intro-image](https://cloud.githubusercontent.com/assets/194400/25710695/e440690a-30e4-11e7-8c62-ed97ce14d706.png)

Combination of: 
https://github.com/dwyl/learn-tachyons/blame/2eda33fc202c75e4210238b0c8b700985611dc4d/README.md#L6
and
http://mrmrs.io/gradients

code:
```
  <body class="bg-teal-gradient white h-100 h5">
    <h1 class="tc ttu f-headline lh-solid mt4 mb0 pb0">Tachyons</h1>
    <h3 class="tc fw1 f3">CSS for designing faster than the speed of light</h3>
    <style>
    .bg-teal-gradient { /** from: http://mrmrs.io/gradients/ **/
      background: rgba(57,204,204,1);
      background: -webkit-linear-gradient(top, rgba(57,204,204,1) 0%, rgba(34,122,122,1) 100%);
      background: linear-gradient(to bottom, rgba(57,204,204,1) 0%, rgba(34,122,122,1) 100%);
    }
    </style>
  </body>
```
