### ISSUE TITLE
Support Tachyons Via OpenCollective

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tachyons#6]
![image](https://cloud.githubusercontent.com/assets/194400/24161841/73a58c6a-0e5d-11e7-93f4-a78fd2073371.png)

@mrmrs we ❤️  the work you're doing. 
Let us know if you're available for dinner on 27th March (_next Monday!_)? see: https://github.com/dwyl/hq/issues/213 
(_if ur not free, no worries_)

**Comment by nelsonic** [comment]
`before`:
![image](https://cloud.githubusercontent.com/assets/194400/24162231/bb7a34c2-0e5e-11e7-8277-26429dd49e4d.png)

`after`:
![image](https://cloud.githubusercontent.com/assets/194400/24162263/dcd2c6f2-0e5e-11e7-87c2-6d5e6517a4bd.png)

Fixed. ✅

**Comment by mrmrs** [comment]
Thanks so much for the support and the invite! I'd love to have dinner next week. Let me know what time to arrive and I will be there.

**Comment by nelsonic** [comment]
@mrmrs people will be here from 18:00 we'll probably eat around 19:30 but arrive when ever you can. ❤️
